DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    salt BLOB NOT NULL,
    hashed_password TEXT NOT NULL,
    deleted BOOLEAN DEFAULT FALSE
);